#ifndef COMBOS_H
#define COMBOS_H

#define JAB           (&jab)
#define CROSS         (&cross)
#define LEFTHOOK      (&leftHook)
#define RIGHTHOOK     (&rightHook)
#define LEFTUPPERCUT  (&leftUppercut)
#define RIGHTUPPERCUT (&rightUppercut)
#define JAB_F           (&jab)
#define CROSS_F        (&cross)
#define LEFTHOOK_F      (&leftHook)
#define RIGHTHOOK_F     (&rightHook)
#define LEFTUPPERCUT_F  (&leftUppercut)
#define RIGHTUPPERCUT_F (&rightUppercut)


#define EASY_PUNCH_TIMEOUT     3000
#define EASY_COMBO_TIMEOUT     5000

#define NORMAL_PUNCH_TIMEOUT   2000
#define NORMAL_COMBO_TIMEOUT   4000

#define ADVANCED_PUNCH_TIMEOUT 800
#define ADVANCED_COMBO_TIMEOUT 2500

#define PRO_PUNCH_TIMEOUT      450
#define PRO_COMBO_TIMEOUT      1250

#define MAX_MOVES 6
#define BLANK nullptr

Servo* EASY_COMBOS[6][MAX_MOVES] = {
  { JAB, CROSS,        BLANK,         BLANK, BLANK, BLANK },
  { JAB, JAB,          BLANK,         BLANK, BLANK, BLANK },
  { JAB, JAB,          CROSS,         BLANK, BLANK, BLANK },
  { JAB, CROSS,          JAB,         BLANK, BLANK, BLANK },
  { JAB, CROSS,     LEFTHOOK,         BLANK, BLANK, BLANK },
  { JAB, RIGHTHOOK,      JAB, RIGHTUPPERCUT, BLANK, BLANK },
};

Servo* NORMAL_COMBOS[6][MAX_MOVES] = {
  { JAB,     CROSS, JAB,      BLANK,         BLANK, BLANK },
  { JAB,       JAB, CROSS,    LEFTHOOK,      BLANK, BLANK },
  { JAB, RIGHTHOOK, LEFTHOOK, RIGHTUPPERCUT, BLANK, BLANK },
  { JAB, CROSS, LEFTHOOK, RIGHTHOOK, BLANK, BLANK },
  { JAB, CROSS, LEFTHOOK, RIGHTHOOK, BLANK, BLANK },
  { JAB, CROSS, LEFTHOOK, RIGHTHOOK, LEFTHOOK, BLANK }

  
};

Servo* ADVANCED_COMBOS[3][MAX_MOVES] = {
  { LEFTHOOK, LEFTHOOK, LEFTHOOK, BLANK, BLANK, BLANK },
  { LEFTHOOK, LEFTHOOK, LEFTHOOK, LEFTHOOK, LEFTHOOK, BLANK },
  { LEFTHOOK, LEFTHOOK, LEFTHOOK, LEFTHOOK, LEFTHOOK, BLANK }
};

Servo* PRO_COMBOS[6][MAX_MOVES] = {
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, },
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, },
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, },
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, },
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, },
  { LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, LEFTUPPERCUT, }
  
};

#endif
